# Generated by Django 4.1.5 on 2023-02-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produitsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produit',
            table='Produits',
        ),
    ]
