# Generated by Django 4.1.5 on 2023-02-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id_client', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_credit', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField(auto_now_add=True)),
                ('a_paye', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Crédits',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='creditsapp.credit')),
            ],
        ),
    ]
