# Generated by Django 4.1.5 on 2023-02-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credit',
            table=None,
        ),
    ]
