# Generated by Django 4.1.5 on 2023-02-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditsapp', '0002_alter_credit_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='a_paye',
            new_name='paid',
        ),
    ]
