# Generated by Django 4.1.5 on 2023-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditsapp', '0003_rename_a_paye_credit_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='paid',
        ),
        migrations.AddField(
            model_name='credit',
            name='est_paye',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_echeance',
            field=models.DateField(),
        ),
    ]
