# Generated by Django 4.1.5 on 2023-02-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='date_De_Emprunt',
            new_name='date_emprunt',
        ),
        migrations.AlterField(
            model_name='chiffre_affaire',
            name='periode',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='date_De_remboursement',
            field=models.DateField(),
        ),
    ]
